services:
  reverse_proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - api_cuda_1
      - api_cuda_2
      - api
  
  api_cuda_1:
    image: ghcr.io/seanghay/tts-inference-server:main
    restart: unless-stopped
    command: gunicorn server:app --worker-class uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  api_cuda_2:
    image: ghcr.io/seanghay/tts-inference-server:main
    restart: unless-stopped
    command: gunicorn server:app --worker-class uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]


  # cpu with 4 workers
  api:
    image: ghcr.io/seanghay/tts-inference-server:main
    restart: unless-stopped
    command: gunicorn server:app --worker-class uvicorn.workers.UvicornWorker --workers 4 --bind 0.0.0.0:80
