services:
  reverse_proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - api_1
      - api_2
      - api_3
  api_1:
    build: .
    restart: unless-stopped
    command: gunicorn server:app --worker-class uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:80
  api_2:
    build: .
    restart: unless-stopped
    command: gunicorn server:app --worker-class uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:80
  api_3:
    build: .
    restart: unless-stopped
    command: gunicorn server:app --worker-class uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:80